### ISSUE TITLE
can‘t download f970619t01p02r02c_rfl.mat ,would you please send it to my email 

### ISSUE THREAD

**Issue by bixiu** [davidkun/HyperSpectralToolbox#8]
because of the internet, it is difficult to download the data from the website directly.would you please send it to my email ,thank you 
my e-mail: qkbing2016@gmail.com

**Comment by davidkun** [comment]
Sorry, the last time I worked on this was during grad school ~6 years ago, so no... I no longer have the files.
I used this site to download the data: https://aviris.jpl.nasa.gov/data/free_data.html, but that was a long time ago. If you're unable to get the data, consider contacting NASA JPL, since they are the ones hosting it.
Thanks and good luck. :-)
