### ISSUE TITLE
I couldn't download f970619t01p02_r02_sc03.a.rfl & f970619t01p02_r02_sc04.a.rfl files.

### ISSUE THREAD

**Issue by khizerali** [davidkun/HyperSpectralToolbox#9]
If you have these files, kindly mail them on khizerali70@gmail.com.

**Comment by davidkun** [comment]
Sorry, the last time I worked on this was during grad school ~6 years ago, so no... I no longer have the files. 
I used this site to download the data: https://aviris.jpl.nasa.gov/data/free_data.html, but that was a long time ago. If you're unable to get the data, consider contacting NASA JPL, since they are the ones hosting it.
Thanks and good luck. :-)
